### ISSUE TITLE
Ubuntu 20.04 LTS Focal Fossa installation instructions

### ISSUE THREAD

**Issue by yaroslav-ilin** [darylounet/libnginx-mod-http-dav-ext#1]
Is it possible to install this package from Package Cloud on Ubuntu 20.04 (`focal`)?
I see that the [Package Cloud page](https://packagecloud.io/app/DaryL/libnginx-mod-http-dav-ext-stable/search?dist=ubuntu%2Ffocal) lists the following packages:
- `libnginx-mod-http-dav-ext_3.0.0+nginx-1.18.0-1~focal_amd64.deb`
- ` libnginx-mod-http-dav-ext_3.0.0+nginx-1.18.0-2~focal_amd64.deb`

However, I don't see any of the corresponding versions of `nginx` available in [the Ubuntu official repository](https://launchpad.net/ubuntu/focal/+source/nginx). It only lists `1.18.0-0ubuntu1` as the latest one so far.

When I run the installation command found on the package page I get the following error:
```sh
~ $ sudo apt-get install libnginx-mod-http-dav-ext=3.0.0+nginx-1.18.0-1~focal
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnginx-mod-http-dav-ext : Depends: nginx (= 1.18.0-1~focal)
E: Unable to correct problems, you have held broken packages.
```

FWIW I have your GPG keys installed correctly.

Am I missing something?

**Comment by darylounet** [comment]
This repository is not intended to be used with distribution packages. You have to use it with the official NGiNX repository :
https://nginx.org/en/linux_packages.html#Ubuntu
But it's true that it is noted nowhere, I should add it in the README.
