### ISSUE TITLE
`dav-ext.conf` enables `PROPFIND` on all servers

### ISSUE THREAD

**Issue by karlvr** [darylounet/libnginx-mod-http-dav-ext#3]
I just discovered I had `PROPFIND` enabled on servers where I wasn't expecting it, which I didn't really like :-) That is because the `dav-ext.conf` file installed by this package adds it outside of a server context.

Is this the expected behaviour?

**Comment by darylounet** [comment]
Hi !
Yes it is expected as an example, like the default NGiNX configuration when you install it.

**Comment by karlvr** [comment]
Thanks for your reply @darylounet ... are you sure this is a good idea? I found it quite unexpected and I considered it a security risk. I was expecting to activate DAV on just the servers I chose.
